import { useMemo, useState } from 'react';
import Header from '../components/layout/Header';
import CalendarView from '../components/calendar/CalendarView';
import { formatDate, isoToday } from '../utils/dateUtils';

const calendarItems = data => [...data.events, ...data.assignments.map(x => ({ id: `assignment-${x.id}`, title: x.title, date: x.dueDate, category: 'School', description: x.description })), ...data.exams.map(x => ({ id: `exam-${x.id}`, title: x.name, date: x.date, category: 'Exam', description: x.coverage })), ...data.projects.map(x => ({ id: `project-${x.id}`, title: x.name, date: x.deadline, category: 'School', description: x.notes })), ...data.tasks.map(x => ({ id: `task-${x.id}`, title: x.title, date: x.dueDate, category: 'Task', description: x.description }))];

export default function Calendar({ data, openModal, remove }) {
  const [monthDate, setMonthDate] = useState(new Date());
  const [view, setView] = useState('Month');
  const events = calendarItems(data);
  const upcoming = events.filter(x => x.date >= isoToday()).sort((a, b) => a.date.localeCompare(b.date));
  const week = useMemo(() => { const start = new Date(); start.setDate(start.getDate() - start.getDay()); return Array.from({ length: 7 }, (_, i) => { const date = new Date(start); date.setDate(start.getDate() + i); return date.toISOString().slice(0, 10); }); }, []);
  const editable = item => !item.id.includes('-') || item.id.startsWith('event-');
  return <><Header title="Calendar" subtitle="See the shape of your week at a glance." onAdd={() => openModal('event')} /><div className="calendar-tabs">{['Month', 'Week', 'Upcoming'].map(tab => <button className={view === tab ? 'active' : ''} onClick={() => setView(tab)} key={tab}>{tab}</button>)}</div><div className="calendar-layout"><div className="panel">{view === 'Month' && <CalendarView events={events} monthDate={monthDate} setMonthDate={setMonthDate} onEdit={x => editable(x) && openModal('event', x)} onDelete={x => editable(x) && remove('events', x)} />}{view === 'Week' && <div className="week-view"><div className="calendar-toolbar"><h2>This week</h2></div>{week.map(day => <div className="week-day" key={day}><b>{formatDate(day, { weekday: 'short', month: 'short', day: 'numeric' })}</b><div>{events.filter(x => x.date === day).map(event => <button className={`calendar-event ${event.category.toLowerCase()}`} onClick={() => editable(event) && openModal('event', event)} key={event.id}>{event.title}</button>)}{!events.some(x => x.date === day) && <span className="muted">Nothing planned</span>}</div></div>)}</div>}{view === 'Upcoming' && <div className="upcoming-view"><div className="section-heading"><div><p className="eyebrow">NEXT 30 DAYS</p><h2>Upcoming events</h2></div></div>{upcoming.length ? upcoming.map(event => <div className="agenda-row" key={event.id}><span className={`item-dot ${event.category.toLowerCase()}`}></span><div><b>{event.title}</b><small>{formatDate(event.date)} · {event.category}</small></div><div className="card-actions">{editable(event) && <><button onClick={() => openModal('event', event)}>✎</button><button onClick={() => remove('events', event)}>×</button></>}</div></div>) : <div className="empty-state"><span>◷</span><h3>Nothing coming up.</h3><p>Your schedule is clear.</p></div>}</div>}</div><aside className="panel calendar-side"><p className="eyebrow">LEGEND</p><h2>Event types</h2>{[['blue','School'],['pink','Personal'],['mint','Task'],['lavender','Exam'],['yellow','Important']].map(([tone, label]) => <div className="legend-row" key={label}><span className={`item-dot ${tone}`}></span>{label}</div>)}<div className="calendar-tip"><span>✦</span><b>Plan softly</b><p>Leave a little breathing room between your commitments.</p></div></aside></div></>;
}
